### ISSUE TITLE
关于Decoder

### ISSUE THREAD

**Issue by wakakaFF** [sd0809/EoFormer#4]
你好，

首先，感谢你的工作。我对您在Decoder上使用边界增强这一想法非常欣赏。所以我有用您的Decoder部分作为我的模型的Decoder，但是

效果并不明显，我想问问是否您的解码器是否需要和编码器配套使用才会有效果？

**Comment by sd0809** [comment]
感谢您对我们工作的关注。
理论上来说并不用，它可以即插即用到你的 decoder 中。可能您需要考虑 EoFormer Block 和您的任务的适配性。
