### ISSUE TITLE
How to set position_embeddings parameters

### ISSUE THREAD

**Issue by avBuffer** [sd0809/EoFormer#5]
How to set position_embeddings parameters

1. In Encoder function:
   position_embeddings=[[None, None], [None, None], [None, None], [None, None]], 

2. run error log:
 File "EoFormer.py", line 20, in __init__
    self.encoder = EHE_encoder(in_chans=self.in_channels, drop_path_rate=drop_path)
  File "encoder_and_decoder.py", line 465, in EHE_encoder
    model = Encoder(
  File "encoder_and_decoder.py", line 335, in __init__
    *[Block(dim=dims[i],
  File "encoder_and_decoder.py", line 335, in <listcomp>
    *[Block(dim=dims[i],
TypeError: Block.__init__() got an unexpected keyword argument 'position_embedding'

**Comment by sd0809** [comment]
Thank you for your interest in our work. 

EoFormer itself does not support position encoding (as I added them in experiments before and did not achieve significant gains), so I removed them afterward. You can modify the EoFormer block yourself to add support for position encoding.
